# Generated by Django 4.1.5 on 2023-02-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('contect', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=15)),
            ],
        ),
    ]
