# Generated by Django 4.1.5 on 2023-02-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contect',
            table='contect',
        ),
    ]
