# Generated by Django 4.1.5 on 2023-03-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_contect_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('contect', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
