# Generated by Django 4.1.5 on 2023-03-11 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('descripaction', models.TextField(max_length=20)),
                ('postby', models.CharField(default='Admin', max_length=20)),
                ('photo', models.ImageField(upload_to='blog/')),
                ('poston', models.DateField(default=datetime.date(2023, 3, 11))),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
