# Generated by Django 4.1.5 on 2023-03-31 04:58

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('descripaction', models.TextField()),
                ('photo', models.ImageField(upload_to='service/')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.DeleteModel(
            name='registration',
        ),
        migrations.AlterField(
            model_name='blog',
            name='descripaction',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 3, 31)),
        ),
    ]
