# Generated by Django 4.1.5 on 2023-04-04 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_service_delete_registration_alter_blog_descripaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 4, 4)),
        ),
        migrations.CreateModel(
            name='serviceitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('photo', models.ImageField(upload_to='items/')),
                ('serviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.service')),
            ],
            options={
                'db_table': 'serviceitem',
            },
        ),
    ]
