# Generated by Django 4.1.5 on 2023-04-12 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_blog_poston'),
    ]

    operations = [
        migrations.CreateModel(
            name='cusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('descripaction', models.TextField()),
                ('photo', models.ImageField(upload_to='service/')),
            ],
            options={
                'db_table': 'cusion',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 4, 12)),
        ),
    ]
