# Generated by Django 4.1.5 on 2023-04-13 04:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cusion_alter_blog_poston'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 4, 13)),
        ),
        migrations.CreateModel(
            name='typecusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('descripaction', models.TextField()),
                ('price', models.FloatField()),
                ('photo', models.ImageField(upload_to='items/')),
                ('cusioneid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cusion')),
            ],
            options={
                'db_table': 'typecusion',
            },
        ),
    ]
