# Generated by Django 4.1.5 on 2023-05-03 04:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_blog_poston'),
    ]

    operations = [
        migrations.AddField(
            model_name='cusion',
            name='serviceitemid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.serviceitem'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 5, 3)),
        ),
    ]
